### ISSUE TITLE
Error report in CGmapIntersect with gzipped files

### ISSUE THREAD

**Issue by Byeong-yong** [guoweilong/cgmaptools#10]
Dear Weilong,

Hello. I used BS-seeker2 to align RRBS data and created CGmap files. But I got an error below when starting to run cgmaptools intersect. Without gzipped file, there was no error.

```
gblab@gblab:/backup/projects/RRBS/bsSeeker/methyl_call$ cgmaptools intersect -1 liver.CGmap.gz -2 muscle.CGmap.gz -o test.gz

Traceback (most recent call last):
  File "/home/gblab/programs/cgmaptools/bin/CGmapIntersect", line 184, in <module>
    main()
  File "/home/gblab/programs/cgmaptools/bin/CGmapIntersect", line 179, in main
    CGmapIntersect(options.CGmap_1, options.CGmap_2, options.context)
  File "/home/gblab/programs/cgmaptools/bin/CGmapIntersect", line 129, in CGmapIntersect
    b"%.2f" % float(methyl_2), b"%d" % int(NmC_2), b"%d" % int(NC_2)]) )
TypeError: sequence item 0: expected str instance, bytes found
```

Can you please help me solve this error? Though I can gunzip every CGmap.gz and use CGmaptools Intersect for now, I want to use gz file next time.

Best,
ByeongYong.

**Comment by guoweilong** [comment]
Hi @Byeong-yong ,

I just update the code to avoid change the format of variable.
You can try to update your local  code, and see if now it works better.

By the way, you can also check if your BAM file is broken?

Look forward to your feedback.

Best,
Weilong

**Comment by IreneZhong918** [comment]
Hi weilong, 
CGmaptools is a wonderful tool for BS-seq visualization, but i met some troubles when i used it to call SNP. 
here is my code:
cgmaptools snv -i MLL3_OFF_161R2_all_call_methylation.ATCGmap.gz -m bayes -v MLL3_OFF_161R2.vcf -o MLL3_OFF_161R2_VCF.snv --bayes-dynamicP

The error is :
# BayesWC mode
# options: use dynamic p-values for different coverages
# options: error rate = 0.050000
Traceback (most recent call last):
  File "/mnt/data/userdata/abao/package_software/cgmaptools-0.1.2/bin/SNVFromATCGmap", line 785, in <module>
    main()
  File "/mnt/data/userdata/abao/package_software/cgmaptools-0.1.2/bin/SNVFromATCGmap", line 780, in main
    options.mode)
  File "/mnt/data/userdata/abao/package_software/cgmaptools-0.1.2/bin/SNVFromATCGmap", line 656, in SNVFromATCGmap
    [NUC, prob_pre, prob_nuc] = SNPfunc( W_A, W_T, W_C, W_G, C_A, C_T, C_C, C_G, nuc)
  File "/mnt/data/userdata/abao/package_software/cgmaptools-0.1.2/bin/SNVFromATCGmap", line 493, in PredictNT_bayes
    [Prob, geno] = max(zip(pstP, ClearSet) + zip(V_pstP, VagueSet) )
TypeError: unsupported operand type(s) for +: 'zip' and 'zip'



Can you please help me solve this error? I have tried to gunzip the ATCGmap.zip , but it still did not work.

Best wishes,
Irene.

**Comment by guoweilong** [comment]
Not sure whether you are working on gizp or zip file.
Maybe you can try :

`zcat MLL3_OFF_161R2_all_call_methylation.ATCGmap.gz | cgmaptools snv -m bayes -v MLL3_OFF_161R2.vcf -o MLL3_OFF_161R2_VCF.snv --bayes-dynamicP`

Best,
Weilong
