### ISSUE TITLE
Errors while trying to run mstat: 

### ISSUE THREAD

**Issue by caitlingilbert** [guoweilong/cgmaptools#38]
Hi there--I've tried to run mstat numerous times now on .CGmap and .CGmap.gz, but it fails despite multiple iterations. Running the latter (.gz format) generates an "IOError: CRC check failed" in gzip.py, while running the .CGmap version generates this error: "File [ .CGmap ] may have wrong number of columns." I've tried running with and without figure-generation, but it keeps hitting these errors. Any thoughts on what I could do to fix this? Thanks so much for building this wonderful tool!!

**Comment by guoweilong** [comment]
@caitlingilbert hi,

The message "File [ .CGmap ] may have wrong number of columns." indicate the input file may not have correct column numbers as defined [CGmap](https://cgmaptools.github.io/cgmaptools_documentation/file-formats.html#cgmap-format)

Sometime it may be broken gzipped file. Maybe you can use `zcat` to see if your input file is valid?

Best,
Weilong

**Comment by caitlingilbert** [comment]
Thanks @guoweilong -- I am able to zcat without issue, and passing the .CGmap.gz file through mstat generates the following error--I'll try to unzip the file again in the meantime, but it doesn't seem to be broken, and the columns appear to match the standard columns for a CGmap file:
`Traceback (most recent call last):
File "/rugpfs/fs0/home/cgilbert/bin/cgmaptools/bin/CGmapStatMeth", line 305, in <module>
    main()
File "/rugpfs/fs0/home/cgilbert/bin/cgmaptools/bin/CGmapStatMeth", line 299, in main
    float(options.fig_height), float(options.fig_width))
File "/rugpfs/fs0/home/cgilbert/bin/cgmaptools/bin/CGmapStatMeth", line 99, in CGmapStatMeth
    line = IN.readline()
File "/rugpfs/fs0/jarv_lab/scratch/cgilbert/bin/anaconda3/envs/py2/lib/python2.7/gzip.py", line 463, in readline
    c = self.read(readsize)
File "/rugpfs/fs0/jarv_lab/scratch/cgilbert/bin/anaconda3/envs/py2/lib/python2.7/gzip.py", line 267, in read
    self._read(readsize)
File "/rugpfs/fs0/jarv_lab/scratch/cgilbert/bin/anaconda3/envs/py2/lib/python2.7/gzip.py", line 314, in _read
    self._read_eof()
File "/rugpfs/fs0/jarv_lab/scratch/cgilbert/bin/anaconda3/envs/py2/lib/python2.7/gzip.py", line 353, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x95bd1ae != 0xb54c4fd6L`

**Comment by guoweilong** [comment]
I see.
As CGmapTools is developted under python2, sometimes using anaconda3 (even specify python 2.7) will cause error.
We have not finished revising it to support python3, although it has been in plan.
Another, you can also see, if top 10000 lines work fine or get same error.

Best,
Weilong
