### ISSUE TITLE
bam2cgmap error

### ISSUE THREAD

**Issue by freyayang** [guoweilong/cgmaptools#56]
Hi, I used bam2cgmap command. But I got an error below: 

Traceback (most recent call last):
  File "/data1/program/cgmaptools/cgmaptools", line 115, in <module>
    subprocess.call([DIR + "/bin/CGmapFromBAM"]+ sys.argv[3:])
  File "/usr/local/python2/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/python2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/python2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Can you help me to figure it out? Thank you!

**Comment by guoweilong** [comment]
Could you send me the full command-line?





Best,
Weilong




At 2022-02-21 22:16:18, "freyayang" ***@***.***> wrote:

Hi, I used bam2cgmap command. But I got an error below:

Traceback (most recent call last):
File "/data1/program/cgmaptools/cgmaptools", line 115, in
subprocess.call([DIR + "/bin/CGmapFromBAM"]+ sys.argv[3:])
File "/usr/local/python2/lib/python2.7/subprocess.py", line 172, in call
return Popen(*popenargs, **kwargs).wait()
File "/usr/local/python2/lib/python2.7/subprocess.py", line 394, in init
errread, errwrite)
File "/usr/local/python2/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

Can you help me to figure it out? Thank you!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
Here is the command:
cgmaptools convert bam2cgmap -b ZH11-1_L2_A001.bsseeker.bam -g IRGSP.Nipponbare.fa --rmOverlap -o ZH11-1

**Comment by guoweilong** [comment]
Maybe you can try the command without specifcy "--rmOverlap" parameter (it not works well for dynamic allocating memory for some system).

Just try: cgmaptools convert bam2cgmap -b ZH11-1_L2_A001.bsseeker.bam -g IRGSP.Nipponbare.fa -o ZH11-1



在 2022-02-21 23:04:45，"freyayang" ***@***.***> 写道：

Here is the command:
cgmaptools convert bam2cgmap -b ZH11-1_L2_A001.bsseeker.bam -g IRGSP.Nipponbare.fa --rmOverlap -o ZH11-1

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
I tried command without '--rmOverlap'. But it came with the same error.

I have a question that I downloaded the code with 'git clone' and got the directory named 'cgmaptools'. I saw there is a file named ' install.sh' in it. Do I need to ' bash install.sh' ? Or I can directly use the cgmaptools command?

**Comment by guoweilong** [comment]
Yes, you need to run the `bash install.sh` before using the commands.



At 2022-02-21 23:22:42, "freyayang" ***@***.***> wrote:

I tried command without '--rmOverlap'. But it came with the same error.

I have a question that I downloaded the code with 'git clone' and got the directory named 'cgmaptools'. I saw there is a file named ' install.sh' in it. Do I need to ' bash install.sh' ? Or I can directly use the cgmaptools command?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
I ran 'bash install.sh'. And the previous error solved. 

I ran the same command line again. But the program stopped abruptly, see below:
![image](https://user-images.githubusercontent.com/42131604/154986137-ba581af2-6481-4075-9a6f-c3869092fda8.png)

what's the problem with this? Thank you!

**Comment by guoweilong** [comment]
Could you re-try this command without the parameter "--rmOverlap"?

Weilong



At 2022-02-21 23:38:28, "freyayang" ***@***.***> wrote:

I ran 'bash install.sh'. And the previous error solved.

I ran the same command line again. But the program stopped abruptly, see below:


what's the problem with this? Thank you!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
I tried both with or without '--rmOverlap', the same problem.

**Comment by guoweilong** [comment]
Maybe you can try to sort the bam file using `samtools sort xx.bam` first, and then use `cgmaptools bam2cgmap`?



At 2022-02-21 23:44:55, "freyayang" ***@***.***> wrote:

I tried both with or without '--rmOverlap', the same problem.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
I have 'sorted.bam' and 'sorted.bam.bai' files which generated by 'bs_seeker2-call_methylation.py'.
I tried the command with this sorted.bam, same problem happened. 
![image](https://user-images.githubusercontent.com/42131604/154988674-5546bfe4-b064-4fb7-9eef-a93b00a626bc.png)

**Comment by guoweilong** [comment]
It seems that your command-line finished quite soon, without any error message.


Maybe you can check if every input file or output file is OK? Or is any file empty?





At 2022-02-21 23:54:07, "freyayang" ***@***.***> wrote:

I have 'sorted.bam' and 'sorted.bam.bai' files which generated by 'bs_seeker2-call_methylation.py'.
I tried the command with this sorted.bam, same problem happened.


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
Hi, my input bam file is generated from 'bsseeker_align.py'. And when I use the same input bam file to run 'bsseeker_call-methylation.py', it works well. However the CGmap result file from bsseeker2_call-methylation.py had very low count number. Almost all lower than 4. So I switch to 'cgmaptools'. Do you think the bam file is not okay? But the bam_report.txt file showed the mappability is ~59%.

**Comment by guoweilong** [comment]
For the case "Almost all lower than 4. ", I think your command runs OK for BS-Seeker2. Maybe you have too many low coverage region, or it is RRBS data?


At least, the CGmap file seems OK in format, but your input reads might be too few to reach enough high coverage.

You can try to remove the sites with very low coverage region. And I also suggest you check your initial input data.





Best,


Weilong








At 2022-02-22 00:07:46, "freyayang" ***@***.***> wrote:

Hi, my input bam file is generated from 'bsseeker_align.py'. And when I use the same input bam file to run 'bsseeker_call-methylation.py', it works well. However the CGmap result file from bsseeker2_call-methylation.py had very low count number. Almost all lower than 4. So I switch to 'cgmaptools'. Do you think the bam file is not okay? But the bam_report.txt file showed the mappability is ~59%.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by freyayang** [comment]
It's not RRBS. I also tried Bismark pipeline with the same initial fastq data, it has much higher count number which looks normal. 
But still, I will check the input file again. Do you have any recommandations for how to check the initial input file? 
Thank you so much!

**Comment by guoweilong** [comment]
Maybe you want to see whether the input or output file size is as you expected. And top lines or tail lines of these files are as you expected.



At 2022-02-22 00:23:18, "freyayang" ***@***.***> wrote:

It's not RRBS. I also tried Bismark pipeline with the same initial fastq data, it has much higher count number which looks normal.
But still, I will check the input file again. Do you have any recommandations for how to check the initial input file?
Thank you so much!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
