### ISSUE TITLE
No image from mstat

### ISSUE THREAD

**Issue by jamespblloyd-uwa** [guoweilong/cgmaptools#63]
Thank you for the great tool. I have been trying to run mstat on some DNA methylomes (see command below). When I set of -f to pdf, I get the below error message and the .data output file has NAs in most of the columns. But if I set -f to data, I get no image file and no error message and the output table is filled with data (as expected). Can you please let me know what I am doing wrong. 

`cgmaptools mstat -i /dd_userdata/usrdat01/userdata/jcahn/Runs/Map/At_MBDs/BS_seeker2/methylcall_ML9/mm2_end_HDG11_HDG12.CGmap.gz -c 5 -f pdf -p ML9_HDG11_HDG12 -t ML9_HDG11_HDG12 > /home/jlloyd/working_data_02/MBD_with_Jon/DNA_methylation/HOME_analysis/20230403_mC_stats/ML9_HDG11_HDG12.pdf

Traceback (most recent call last):
  File "/home/jlloyd/working_data_02/bin/cgmaptools-0.1.2/bin/CGmapStatMeth", line 305, in <module>
    main()
  File "/home/jlloyd/working_data_02/bin/cgmaptools-0.1.2/bin/CGmapStatMeth", line 299, in main
    float(options.fig_height), float(options.fig_width))
  File "/home/jlloyd/working_data_02/bin/cgmaptools-0.1.2/bin/CGmapStatMeth", line 194, in CGmapStatMeth
    if count_mC_byChr[chr][i]>0 else "NaN" for i in xrange( len(context_lst) ) ]) )
TypeError: sequence item 1: expected str instance, bytes found`

**Comment by guoweilong** [comment]
It might be a python version related issue. You may try the new release v0.1.3, which is supposed to support python 3.
